image: node:14

cache:
    paths:
      - node_modules/

stages:
  - build
  - test

install:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
 
test:       # This job runs in the build stage, which runs first.
  stage: test
  script:
    - npm run test
    - npm run lint
    - npm run format

test_2:
  stage: test
  script:
    - npm run build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH