image: node:16

stages:
  - pre-build
  - build
  - deploy

variables:
  NETLIFY_API_ID: $NETLIFY_API_ID
  NETLIFY_AUTH_TOKEN: $NETLIFY_AUTH_TOKEN

install:
  stage: pre-build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/


# build-job:
#   stage: build
#   script:
#     - npm run lint
#     - npm run format
#     - npm run test
#   cache:
#     paths:
#       - node_modules/

build-job2:
  stage: build
  script:
    - npm run build
  artifacts: 
    paths: 
      - public/
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy-prod:
  stage: deploy
  script:
    - npx netlify-cli deploy --site "$NETLIFY_API_ID" --auth "$NETLIFY_AUTH_TOKEN" --prod
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
